"""create category

Revision ID: 390fed9692ce
Revises: 36a36591d7d3
Create Date: 2024-02-23 22:57:51.221422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390fed9692ce'
down_revision = '36a36591d7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['description'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
