"""add category to book

Revision ID: 51358bb20a09
Revises: d768d41412a8
Create Date: 2024-02-23 03:49:02.096931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51358bb20a09'
down_revision = 'd768d41412a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
